# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/adda.xdc

# Block Designs: bd/design_mb/design_mb.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb || ORIG_REF_NAME==design_mb} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_microblaze_0_0/design_mb_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_microblaze_0_0 || ORIG_REF_NAME==design_mb_microblaze_0_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_dlmb_v10_0/design_mb_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_dlmb_v10_0 || ORIG_REF_NAME==design_mb_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_ilmb_v10_0/design_mb_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_ilmb_v10_0 || ORIG_REF_NAME==design_mb_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_dlmb_bram_if_cntlr_0/design_mb_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_mb_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_ilmb_bram_if_cntlr_0/design_mb_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_mb_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_lmb_bram_0/design_mb_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_lmb_bram_0 || ORIG_REF_NAME==design_mb_lmb_bram_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_mdm_1_0/design_mb_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_mdm_1_0 || ORIG_REF_NAME==design_mb_mdm_1_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_clk_wiz_1_0/design_mb_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_clk_wiz_1_0 || ORIG_REF_NAME==design_mb_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_rst_clk_wiz_1_100M_0/design_mb_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_mb_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_uartlite_0_0/design_mb_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_axi_uartlite_0_0 || ORIG_REF_NAME==design_mb_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_xbar_0/design_mb_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_xbar_0 || ORIG_REF_NAME==design_mb_xbar_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_microblaze_0_axi_periph_0/design_mb_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_mb_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_gpio_0_0/design_mb_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_axi_gpio_0_0 || ORIG_REF_NAME==design_mb_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_gpio_1_0/design_mb_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_axi_gpio_1_0 || ORIG_REF_NAME==design_mb_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_gpio_2_0/design_mb_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_axi_gpio_2_0 || ORIG_REF_NAME==design_mb_axi_gpio_2_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_intc_0_0/design_mb_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_axi_intc_0_0 || ORIG_REF_NAME==design_mb_axi_intc_0_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_xlconcat_0_0/design_mb_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_xlconcat_0_0 || ORIG_REF_NAME==design_mb_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_timer_0_0/design_mb_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_axi_timer_0_0 || ORIG_REF_NAME==design_mb_axi_timer_0_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_uartlite_1_1/design_mb_axi_uartlite_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_axi_uartlite_1_1 || ORIG_REF_NAME==design_mb_axi_uartlite_1_1} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_uartlite_2_1/design_mb_axi_uartlite_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_axi_uartlite_2_1 || ORIG_REF_NAME==design_mb_axi_uartlite_2_1} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_quad_spi_0_0/design_mb_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_axi_quad_spi_0_0 || ORIG_REF_NAME==design_mb_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_axi_quad_spi_1_0/design_mb_axi_quad_spi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_axi_quad_spi_1_0 || ORIG_REF_NAME==design_mb_axi_quad_spi_1_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_system_ila_0_0/design_mb_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_system_ila_0_0 || ORIG_REF_NAME==design_mb_system_ila_0_0} -quiet] -quiet

# IP: bd/design_mb/ip/design_mb_auto_pc_0/design_mb_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_mb_auto_pc_0 || ORIG_REF_NAME==design_mb_auto_pc_0} -quiet] -quiet

# XDC: bd/design_mb/design_mb_ooc.xdc
